### ISSUE TITLE
Sorry I have problem with makefile under Linux - Error!

### ISSUE THREAD

**Issue by DeafMan1983** [edgarbarney/halflife-planckepoch#26]
Hello please fix for linux!

Looke my screenshot:
![image](https://github.com/edgarbarney/halflife-planckepoch/assets/57066679/5e826e74-de4d-4fb7-b17e-01d0f0773e3b)

Because Spirinity has directory for linux. How do I compile successfully?

**Comment by edgarbarney** [comment]
Hello

Since original Trinity is Windows exclusive, unfortunately, so is Spirinity. 

I can try to port it in the future, but since I'm not actively working on this project for some time, I have no plans for it.

After I finish the new audio system, I may start porting it to Linux.

But like I said, for now, there's no way to build Spirinity on Linux and a possible Linux port is pretty far away.

EDIT: Also, I'll remove makefiles for now to avoid further confusion about the Linux build.

**Comment by DeafMan1983** [comment]
Good idea! Please replace with Glew 2.x because it is cross platform.  I will wait for release. 💪
