### ISSUE TITLE
Water isnt working for me, aswell as any reflective surfaces. NOTE : on steam version

### ISSUE THREAD

**Issue by bacontsu** [edgarbarney/halflife-planckepoch#6]
Water isnt working for me, aswell as any reflective surfaces. Instead they reflect my whole screen instead of the levels. am i doing something wrong? Solokiller said that on steam version trinity wasnt really supported because it was made for old build of half life, and those whole new opengl stuff could broke stuffs. but looks like you managed to get it working nicely, how did you do it?

**Comment by edgarbarney** [comment]
Unfortunately, reflections are not working very well in the Fullscreen mode of the Steam version but I've made a small fix in v0.4. You should enable windowed mode with your native screen resolution, then use "r_borderless 1" and "r_ignoreborderless 1" cvar to enable borderless fullscreen mode. 

Just like Solokiller said, the steam version was not really supported. I've fiddled a bit with SDL libraries and merged with Solokiller's Updated SDK. It's now working fairly good. But sometimes "fairly good" is not being enough because of the engine limitations and trinity's old code combined, so hacks like my custom borderless fullscreen mode gains usage.

**Comment by bacontsu** [comment]
> Unfortunately, reflections are not working very well in the Fullscreen mode of the Steam version but I've made a small fix in v0.4. You should enable windowed mode with your native screen resolution, then use "r_borderless 1" and "r_ignoreborderless 1" cvar to enable borderless fullscreen mode.
> 
> Just like Solokiller said, the steam version was not really supported. I've fiddled a bit with SDL libraries and merged with Solokiller's Updated SDK. It's now working fairly good. But sometimes "fairly good" is not being enough because of the engine limitations and trinity's old code combined, so hacks like my custom borderless fullscreen mode gains usage.

ahh aight, thanks so much for the answer dude!. theres 2 solution to this then, using borderless fullscreen or using -nofbo args, eventho -nofbo made a new bug to the anisotropic filtering. by the way im also in TWHL discord!

**Comment by edgarbarney** [comment]
@bacontsu Both should work but I've made my "borderless mode" hack by working with SDL library, so without buggering up the FBO or the Anisotropy, you can safely use r_borderless 1 in new version.

**Comment by bacontsu** [comment]
i see, imma try that asap. thanks man!
